import Head from 'next/head';
import { useRouter } from 'next/router';
import Link from 'next/link';
import React from 'react';
import Button from '../../components/Button';
import Cta from '../../components/Cta';
import Div from '../../components/Div';
import Layout from '../../components/Layout';
import PageHeading from '../../components/PageHeading';
import SectionHeading from '../../components/SectionHeading';
import Spacing from '../../components/Spacing';
import Sidebar from '../../components/Sidebar.jsx/index.jsx';
import firebaseApp from '../../firebase/firebaseConfig';
import firebaseConfig from '../../firebase/firebaseConfig';
import { getFirestore, collection, query, where, getDocs  } from 'firebase/firestore';
import { Icon } from '@iconify/react';
import { useEffect, useState } from 'react';


export default function CategoryDetails() {
  const router = useRouter();
  const categoryId = router.query.categoryId;
  const db = getFirestore(); 

  useEffect(() => {
    const container = document.getElementById("cardContainer");

    async function fetchData() {
      if (categoryId) {
      const q = query(collection(db, 'PortfolioDetails'), where('portfolio_category', '==', categoryId));

      try {
        const querySnapshot = await getDocs(q);

        querySnapshot.forEach((doc) => {
          const data = doc.data();
          const docId = doc.id;
          createCard(data, docId);
          console.log(doc.data);
        });
      } catch (error) {
        console.error('Error fetching data:', error);
      }
      }
    }

    function createCard(data, docId) {
      const cardDiv = document.createElement("div");
      cardDiv.classList.add("col-lg-4", "col-sm-6");
      const portfolioURL = `/portfolio-details/${docId}`;

      const cardContent = `
        <Div className="cs-team cs-style2">
          <Div className="cs-member_thumb">
            <img src="${data.imageURL}" alt="Member">
            <Div className="cs-member_overlay"></div>
          </Div>
          <Div className="cs-member_info">
            <h4 className="cs-member_name mt-4"><a href="${portfolioURL}">${data.portfolio_title}</a></h4>
            <Div className="cs-member_designation" id="date">${data.portfolio_date}</Div>
          </Div>
        </Div>
        <Div class="cs-height_80 cs-height_lg_30"></Div>
      `;

      cardDiv.innerHTML = cardContent;
      container.querySelector(".row").appendChild(cardDiv);
    }

    fetchData();
  }, [categoryId, db]);

  

 const createMarkup = (content) => {
  return { __html: content };
};  
  
  return (
    <>
      <Head>
        <title>Portfolio - {categoryId}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
     
        <PageHeading
          title="Portfolio Details"
          bgSrc={"/images/service_hero_bg.jpeg"}
          pageLinkText={categoryId}
        />
        <Spacing lg="150" md="80" />
       
        <Div id="cardContainer"  className="container">
          <Div className="row">
            </Div></Div>
        
        <Spacing lg="145" md="80" />
        <Cta
          title="siddhant@tebble.com"
          bgSrc="/images/cta_bg_2.jpeg"
          variant="rounded-0"
          
        />
        
      </Layout>
    </>
  );
}
